// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM8_VWSHUrdkdwmaoZpsX2ZOTtvyqwVrU',
    appId: '1:541856290759:web:88361522f10cc62f02ebe2',
    messagingSenderId: '541856290759',
    projectId: 'flutter-authen-cb356',
    authDomain: 'flutter-authen-cb356.firebaseapp.com',
    storageBucket: 'flutter-authen-cb356.firebasestorage.app',
    measurementId: 'G-H2LXRC6NL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ4HlmUkWGjWiwDGEuefxNo-pPJ3rFQZo',
    appId: '1:541856290759:android:8e12208586b1de9002ebe2',
    messagingSenderId: '541856290759',
    projectId: 'flutter-authen-cb356',
    storageBucket: 'flutter-authen-cb356.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEG8O6BeTILiYvsow9oq4GNGBq8yDWuoU',
    appId: '1:541856290759:ios:876d0aa10370762702ebe2',
    messagingSenderId: '541856290759',
    projectId: 'flutter-authen-cb356',
    storageBucket: 'flutter-authen-cb356.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEG8O6BeTILiYvsow9oq4GNGBq8yDWuoU',
    appId: '1:541856290759:ios:876d0aa10370762702ebe2',
    messagingSenderId: '541856290759',
    projectId: 'flutter-authen-cb356',
    storageBucket: 'flutter-authen-cb356.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM8_VWSHUrdkdwmaoZpsX2ZOTtvyqwVrU',
    appId: '1:541856290759:web:13b981b8d590255502ebe2',
    messagingSenderId: '541856290759',
    projectId: 'flutter-authen-cb356',
    authDomain: 'flutter-authen-cb356.firebaseapp.com',
    storageBucket: 'flutter-authen-cb356.firebasestorage.app',
    measurementId: 'G-7870T1QZ84',
  );
}
